### ISSUE TITLE
pretrained model?

### ISSUE THREAD

**Issue by tlwzzy** [xavier-zw/tDenseRNN_pose#4]
Thanks for your great job, how can I get tDense.pth for inference?

**Comment by xavier-zw** [comment]
Thank you for your attention.We have organized a portion of sample data and pre-trained models for validating our approach. All subsequent data and pre-trained models will be made fully available to the public.The access link has been updated in our Readme.
















At 2023-12-19 17:02:51, "dlutzy" ***@***.***> wrote:

Thanks for your great job, how can I get tDense.pth for inference?
